name: CB
on: 
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/resuable-workflow.yml
    with:
      env: prod
    secrets: 
      token: ${{ secrets.DOCKER_TOKEN }}
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: print
        run: echo " ${{ needs.build.outputs.version }}"
      
