name: condition
on:
  push:
    branches: master
    paths: .github/workflows/conditional.yml
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: step1
        if: ${{ github.ref_name == 'master' }}
        uses: actions/checkout@v7
      - id: step2
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: exit 1
      - name: step3
        if: failure()
        run: echo "last step failed"
      - name: step4
        if: ${{ github.event_name == 'push' && success() }}
        run: echo "correct event"
        
        
        
      
