name: Continous Integration
on:
  push:  
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v7    
      - name: setup-node-test-lint
        uses: ./.github/actions/node-setup/
        with:
          node-version: 20
          cache-dependency-path: frontend/package-lock.json
          code_path: frontend/ 
      - name: docker-login-push
        if: ${{ github.ref_name == 'master' }}
        uses: ./.github/actions/docker-setup
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          code-path: frontend       
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v7
      - name: go-setup-test
        uses: ./.github/actions/go-setup/
        with:
          go-version: 1.23
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
          code-path: backend/ 
      - name: docker-login-push
        if: ${{ github.ref_name == 'master' }}
        uses: ./.github/actions/docker-setup
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          code-path: backend
