name: ghhosted
on: 
  workflow_dispatch:

jobs:
  job1:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-slim, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: OS name
        run: cat /etc/os-release | grep "PRETTY_NAME"
      - name: hostname
        run: hostname
      - name: current user
        run: whoami
  job2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: docker version
        run: docker version
      - name: git
        run: git version
      - name: python
        run: python version
      - name: node
        run: npm version

