name: Hello
on:
  workflow_dispatch:
jobs:
  code-checkout-hello:
    runs-on: ubuntu-latest
    steps:
      - name: code_checkout
        uses: actions/checkout@v7
      - name: hello
        run: echo "hello from github actions"
      - name: date
        run: date
      - name: branch-name
        run:  echo " the branch is ${{ github.ref_name }}"
      - name: files-in-repo
        run: ls -l
      - name: host-os
        run: hostname
        
  
  

