name: main
on:
  workflow_dispatch:

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - name: code-chekcout
        uses: actions/checkout@v7
      - name: install
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: cache-dependencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          
      - name: build
        run: |
          cd frontend
          npm install
          npm run build
          
      - id: cache
        uses: actions/cache@v6
        with: 
          path: frontend/dist/
          key: ${{ runner.os }}-node-build-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-build-
          
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: main_file
          path: frontend/dist/
        
