name: main
on:
  workflow_dispatch:

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - name: code-chekcout
        uses: actions/checkout@v7
      - id: cache-d
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install
        if: steps.cache-d.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20   
     
      - name: print
        run: |
          cd frontend/dist/
          ls -l
          
        
