name: matrix
on: 
  workflow_dispatch:
jobs:
  first:
    strategy:
      matrix:
        exclude:
          - os: ubuntu-slim
            python: 3.10
        os: [ ubuntu-latest , ubuntu-slim ]
        python: ['3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - name: installation
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          
  
