name: multijob
on:
  push: 
    branches: master

jobs:
  code:
    runs-on: [self-hosted, linux-practice]
    steps:
      - name: code checkout
        uses: actions/checkout@v7
  build:
    runs-on: [self-hosted, linux-practice]
    needs: code
    steps:
      - name: build
        run: echo "build successful"
  test:
    runs-on: [self-hosted, linux-practice]
    needs: build
    steps:
      - name: test
        run: echo "test completed, all test passed"
  deploy:
    needs: test
    runs-on: [self-hosted, linux-practice]
    steps:
      - name: deploy
        run: echo "ready to deploy"
