name: repo-dispatch
on: 
  repository_dispatch:
    types: [deploy-event]

jobs:
 job1:
   runs-on: ubuntu-latest
   steps:
     - name: print
       run: echo "${{ github.event.client_payload.environment }}"
     
