name: RE
on:
  workflow_call:
    outputs:
      data:
        description: "version id "
        value: ${{ jobs.job1.outputs.out1 }}
    inputs:
      env:
        type: string
        default: 'staging'
        required: true
      app_name:
        type: string
        required: false
    secrets:
      token:
        required: true
  
jobs:
  job1:
    outputs:
      out1: ${{ steps.v1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: code
        uses: actions/checkout@v7
      - name: print
        run: echo " building ${{ inputs.app_name }} for ${{ inputs.env }}"
      - name: token
        run: echo "dokcer token is set ${{ secrets.token }}"
      - id: v1
        run: |
          echo "version=v1.0.app" >> "$GITHUB_OUTPUT"
        
        
        
