name: schedule
on:  
  schedule:
    - cron: '1 */1 * * *'
  workflow_dispatch:   
jobs: 
  health:
    env:
      url: ${{ 'http://google.com' }}
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
          STATUS_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" $url)
          echo "HTTP Status Code: $STATUS_CODE"

          if [ $STATUS_CODE -ne 200 ]; then
            echo "wrong status code"
            exit 1
          fi
