name: secret
on: 
  workflow_dispatch:
jobs:
  job1:
    env:
      secret: ${{ secrets.MY_SECRET_MESSAGE }}
    runs-on: ubuntu-latest
    steps:
      - name: status
        if:  ${{ '$secret' == '' }}
        run: echo "does not exist" 
      - name: print
        run: echo " ${{ secrets.MY_SECRET_MESSAGE }}"
        

  
