name: security
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      secret: ${{ secrets.SuperSecret }}
    steps:
      - name: print
        if: ${{ env.secret == '' }}
        run: "secret is empty"
      - name: status]
        env:
          name: 'rohit'
        run: |
          echo " ${{ secrets.SuperSecret }}" 
          echo env.name

  
