name: sfhosted
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: [self-hosted, linux-practice]
    strategy:
      fail-fast: false
    steps:
      - name: docker
        run: docker version
      - name: whoami
        run: whoami
      - name: hostname
        run: hostname
  
