name: sfhosted
on:
  push:
    branches: master
    paths: .github/workflows/self_hosted.yml
  workflow_dispatch:

jobs:
  job1:
    outputs:
      out1: ${{ steps.step1.outputs.text }}
      out2: ${{ steps.step2.outputs.text }}
      out3: ${{ steps.step3.outputs.text }}
      
    runs-on: [self-hosted, linux-practice]
    strategy:
      fail-fast: false
    steps:
      - id: step1
        run: |
          version=$(docker --version)
          echo "text=$version" >> "$GITHUB_OUTPUT"
      - id: step2
        run: |
          version=$(whoami)
          echo "text=$version" >> "$GITHUB_OUTPUT"
      - id: step3
        run: |
          version=$(hostname)
          echo "text=$version" >> "$GITHUB_OUTPUT"
   
  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      d: ${{ needs.job1.outputs.out1 }}
      w: ${{ needs.job1.outputs.out2 }}
      h: ${{ needs.job1.outputs.out3 }}
    steps:
      - name: docker
        run: echo "$d"
      - name: whoami
        run: echo "$w"
      - name: hostname
        run: echo "$h"
      
    
