name: sp
on:
  push:  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lintjob
        run: echo "lint job running"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testjob
        run: echo "test job is running"
  summary:
    runs-on: ubuntu-latest
    needs: [ lint,test ]
    steps:
      - name: branch
        if: ${{ github.ref_name == 'master' }}
        run: echo "this is master branch"
      - name: feature
        if: ${{ github.ref_name == 'dev' }}
        run: echo "this dev branch"
      - name: commit
        run: echo " ${{ github.event.head_commit.message }}"
