name: trigger2
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: 
jobs:
  second:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: t2
        run: echo "scheduled job for the pull request"
    
